apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: zipkin
  namespace: gitops
spec:
  type: exporters.zipkin
  metadata:
  - name: enabled
    value: "true"
  - name: exporterAddress
    value: "http://zipkin.dapr-monitoring.svc.cluster.local:9411/api/v2/spans"