apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: gitops-config
  namespace: gitops
spec:
  tracing:
    samplingRate: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops
  namespace: gitops
  labels:
    app: gitops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "gitops"
        dapr.io/app-protocol: "http"
        dapr.io/app-port: "8080"
        dapr.io/config: "gitops-config"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: service
        image: ghcr.io/mchmarny/git-ops:v0.4.20
        ports:
        - containerPort: 8080
        env:
        - name: ADDRESS
          value: ":8080"