name: git-ops release on tag

on:
  push:
    tags:
      - 'v*' # v-v0.1.1

jobs:

  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

    - name: Setup
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Checkout
      id: setup
      uses: actions/checkout@v2

    - name: Tidy
      run: |
        go mod tidy 
        go mod vendor

    - name: Test
      run: |
        go test -v -count=1 -race ./...

    - name: Variables
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
        BUILD_TIME=$(echo $(date +"%Y-%m-%dT%T"))
        echo "BUILD_TIME=${BUILD_TIME}" >> $GITHUB_ENV

    - name: Push
      uses: docker/build-push-action@v1
      with:
        context: .
        file: ./Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.actor }}/git-ops-demo/git-ops-app
        push: true
        tags: ${{ env.RELEASE_VERSION }}
        build-args: |
            APP_VERSION=${{ env.RELEASE_VERSION }}
            BUILD_TIME=${{ env.BUILD_TIME }}
  
