name: git-ops release on tag

on:
  push:
    tags:
      - 'v*' # v-v0.1.1

jobs:

  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

    - name: Setup
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Checkout
      id: setup
      uses: actions/checkout@v2

    - name: Tidy
      run: |
        go mod tidy 
        go mod vendor

    - name: Test
      run: |
        go test -v -count=1 -race ./...

    - name: Variables
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo $(date -u +"BUILD_TIME=%Y-%m-%dT%T-UTC") >> $GITHUB_ENV

    - name: Info
      run: |
        echo "::debug::RELEASE_VERSION=${{ env.RELEASE_VERSION }}"
        echo "::debug::BUILD_TIME=${{ env.BUILD_TIME }}"

    - name: Push
      uses: docker/build-push-action@v1
      with:
        context: .
        file: ./Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.OPS_TOKEN }}
        registry: ghcr.io
        push: true
        tags: ${{ env.RELEASE_VERSION }},latest
        build_args: APP_VERSION=${{ env.RELEASE_VERSION }},BUILD_TIME=${{ env.BUILD_TIME }}

    - name: Context
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        clusterName: ${{ secrets.AZURE_CLUSTER_NAME }}
      id: login

    - name: Publish
      uses: Azure/k8s-deploy@v1
      with:
        namespace: gitops
        kubectl-version: latest
        manifests: k8s/deployment.yaml
        images: ghcr.io/mchmarny/git-ops:${{ env.RELEASE_VERSION }}
        